import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import One from "./one";
import Two from "./two";
import Three from "./three";
import Four from "./four";
import Five from "./five";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isDarkMode, setIsDarkMode] = useState(false);

  useEffect(() => {
    const storedIsDarkMode = localStorage.getItem("isDarkMode");
    if (storedIsDarkMode !== null) {
      setIsDarkMode(JSON.parse(storedIsDarkMode));
    }
  }, []);

  useEffect(() => {
    if (isDarkMode) {
      document.documentElement.style.backgroundColor = "#1a1a1a";
      document.documentElement.style.color = "#f1f1f1";
    } else {
      document.documentElement.style.backgroundColor = "#f1f1f1";
      document.documentElement.style.color = "#1a1a1a";
    }

    localStorage.setItem("isDarkMode", JSON.stringify(isDarkMode));
  }, [isDarkMode]);

  const toggleDarkMode = () => {
    setIsDarkMode(!isDarkMode);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="wrap">
        <button
          className={
            isDarkMode
              ? "darkBtn dark"
              : "darkBtn"
          }
          onClick={toggleDarkMode}
        >
          {isDarkMode ? "Dark" : "Light"}
        </button>
        <One />
        <Two />
        <Three />
        <Four />
        <Five />
      </div>
    </>
  );
}
